Script started on 2015年03月14日 (週六) 10時47分13秒
]0;F74036239@2015cpp: ~F74036239@2015cpp:~$ whoami;pwd
F74036239
/home/F74036239
]0;F74036239@2015cpp: ~F74036239@2015cpp:~$ git config -l
user.name=F74036239
user.email=lu12345cyxie@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/F74036239/lab1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
]0;F74036239@2015cpp: ~F74036239@2015cpp:~$ git clone https://github.com/F74036239/lab1.g it
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;F74036239@2015cpp: ~F74036239@2015cpp:~$ git clone https://github.com/F74036239/lab1.giit[A]0;F74036239@2015cpp: ~F74036239@2015cpp:~$ [C[C[C[C[Config -l[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[3Pwhoami;pwd[3Pcd lab1ls[Kcd ..[3Plsrm running.scriptls[Kcd ..[3Plscd lab1whoami;pwdgit config -llone https://github.com/F74036239/lab1.giit[A]0;F74036239@2015cpp: ~F74036239@2015cpp:~$ [K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cgit clone https://github.com/F74036239/lab1.giit[A]0;F74036239@2015cpp: ~F74036239@2015cpp:~$ [C[C[C[C[Config -l[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[3Pwhoami;pwd[3Pcd lab1whoami;pwdgit config -llone https://github.com/F74036239/lab1.giit[A]0;F74036239@2015cpp: ~F74036239@2015cpp:~$ [K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Crm -r -f lab1
]0;F74036239@2015cpp: ~F74036239@2015cpp:~$ ls
lab1.script
]0;F74036239@2015cpp: ~F74036239@2015cpp:~$ lsrm -r -f lab1git clone https://github.com/F74036239/lab1.giit
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F74036239@2015cpp: ~F74036239@2015cpp:~$ exit

Script done on 2015年03月14日 (週六) 10時48分00秒
